name: "⭐ 기능 / 개선사항"
description: 새로운 무언가를 제안해주세요.

labels:
  - enhancement
  - Triage-Needed
body:
  - type: markdown
    attributes:
      value: |
        이슈를 제안하기 전에 [기존의 이슈](https://github.com/miho73/ion/issues)를 확인해주세요!

  - type: textarea
    attributes:
      label: 새로운 기능이나 개선 사항을 설명해주세요.
      placeholder: 이 기능은 어떻게 작동해야 하나요?
    validations:
      required: true

  - type: textarea
    attributes:
      label: 보조 정보
      placeholder: 추가적인 정보, 구현 사항, 예시를 들어주세요. 기능 구현에 도움이 됩니다.
    validations:
      required: false

